global prefixPresets, suffixPresets, containPresets, mapPresets
prefixPresets = #(
#("Left/Right", "Left", "Right"),
#("L/R", "L", "R"),
#("L_/R_", "L_", "R_"),
#("Bip001 L /Bip001 R ", "Bip001 L ", "Bip001 R ")
)
suffixPresets = #(
#("_L/_R", "_L", "_R"),
#("_left/_right", "_left", "_right"),
#("Left/Right", "Left", "Right")
)
containPresets = #(
#("Left/Right words", "Left", "Right"),
#("L/R mix", "L", "R")
)
mapPresets = #(
#("SuperHero", "SpiderMan_01=BatMan_114514"),
#("两个傻逼", "冥月千雪=你的中二魔王\n你的中二魔王=绝世大傻逼\nDante陽=绝世大傻逼\n你的中二魔王=Dante陽")
)

